### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Teicu** [joshkar/X-Recon#2]
While the current approach scans all pages, perhaps we could explore filtering to prioritize pages containing input parameters, which are often more susceptible to security risks. 

Is there an option to configure to test only pages with input parameters? 

Cheers

**Comment by joshkar** [comment]
Hi,

I will add this to the update list for X-Recon. It's an interesting suggestion. If you have any specific solutions or workflows for this, please share them with me to help improve the tool more efficiently.

**Comment by joshkar** [comment]
> While the current approach scans all pages, perhaps we could explore filtering to prioritize pages containing input parameters, which are often more susceptible to security risks.
> 
> Is there an option to configure to test only pages with input parameters?
> 
> Cheers

Hi,

I will add this to the update list for X-Recon. It's an interesting suggestion. If you have any specific solutions or workflows for this, please share them with me to help improve the tool more efficiently.
