### ISSUE TITLE
Unable to perform XSS scan 

### ISSUE THREAD

**Issue by jasonthename** [joshkar/X-Recon#3]
"No File For Scan"  after selecting option 2.

I'm trying to do a XSS scan without the recon part.

Can I perhaps, input my own URLs without the tool doing recon?

**Comment by joshkar** [comment]
> "No File For Scan" after selecting option 2.
> 
> I'm trying to do a XSS scan without the recon part.
> 
> Can I perhaps, input my own URLs without the tool doing recon?

Hi,

No, this is not possible because option 2 uses a custom JSON for the scanning process, and creating this custom JSON requires using option 1.

In the future, we will provide the ability to create custom JSONs based on desired URLs and parameters.
